#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shlex
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any
from urllib.parse import urlparse
from urllib import error, request


REPO_ROOT = Path(__file__).resolve().parent.parent
VERSION_SENSITIVE_VLLM_FLAGS = [
    "--data-parallel-size",
    "--data-parallel-size-local",
    "--api-server-count",
    "--enable-auto-tool-choice",
    "--tool-call-parser",
]


def _runtime_root(path: str) -> Path:
    return Path(path).expanduser().resolve()


def _load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n", encoding="utf-8")


def _parse_env_pair(raw: str) -> tuple[str, str]:
    if "=" not in raw:
        raise argparse.ArgumentTypeError(f"expected KEY=VALUE, got: {raw!r}")
    key, value = raw.split("=", 1)
    key = key.strip()
    if not key:
        raise argparse.ArgumentTypeError(f"empty env var name in: {raw!r}")
    return key, value


def _normalize_api_base(raw: str) -> str:
    api_base = raw.rstrip("/")
    if not api_base.endswith("/v1"):
        api_base = api_base + "/v1"
    return api_base


def _resolve_path_from_repo(path: str) -> Path:
    candidate = Path(path).expanduser()
    if candidate.is_absolute():
        return candidate.resolve()
    repo_relative = (REPO_ROOT / candidate).resolve()
    if repo_relative.exists():
        return repo_relative
    return candidate.resolve()


def _public_endpoint(
    *,
    host: str,
    port: int,
    public_host: str | None,
    public_port: int | None,
    public_base_url: str | None,
) -> tuple[str, str, str]:
    """Return public host/port/api_base for clients and task logs."""
    if public_base_url:
        api_base = _normalize_api_base(public_base_url)
        parsed = urlparse(api_base)
        if not parsed.scheme or not parsed.netloc:
            raise argparse.ArgumentTypeError(f"invalid --public-base-url: {public_base_url!r}")
        return parsed.hostname or public_host or host, str(parsed.port or public_port or port), api_base

    resolved_public_host = public_host or host
    resolved_public_port = str(public_port or port)
    api_base = _normalize_api_base(f"http://{resolved_public_host}:{resolved_public_port}")
    return resolved_public_host, resolved_public_port, api_base


def _build_launch_script(template_path: Path, env_vars: dict[str, str]) -> str:
    template_text = template_path.read_text(encoding="utf-8")
    template_lines = template_text.splitlines()
    if template_lines and template_lines[0].startswith("#!"):
        template_lines = template_lines[1:]
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by sh/run_remote_inference_task.py",
        "",
    ]
    for key, value in sorted(env_vars.items()):
        lines.append(f"export {key}={shlex.quote(value)}")
    lines.extend(["", *template_lines, ""])
    return "\n".join(lines)


def _generated_script_name(template_path: Path) -> str:
    stem = template_path.stem
    return f"{stem}.generated.sh"


def _request_paths(runtime_root: Path, template_path: Path) -> tuple[Path, Path]:
    return (
        runtime_root / "remote-inference" / _generated_script_name(template_path),
        runtime_root / "inference_task.request.json",
    )


def _task_state_path(runtime_root: Path) -> Path:
    return runtime_root / "inference_task.json"


def _probe_path(runtime_root: Path) -> Path:
    return runtime_root / "inference_probe.json"


def _normalize_optional_api_base(raw: Any) -> str:
    if not raw:
        return ""
    return _normalize_api_base(str(raw))


def _script_mentions_flag(script_text: str, flag: str) -> bool:
    quoted = f'"{flag}"'
    return flag in script_text or quoted in script_text


def _run_help_command(binary: str) -> dict[str, Any]:
    resolved = shutil.which(binary)
    if not resolved:
        return {
            "ok": False,
            "binary": binary,
            "error": f"binary not found on PATH: {binary}",
        }
    try:
        proc = subprocess.run(
            [resolved, "serve", "--help"],
            capture_output=True,
            text=True,
            check=False,
            timeout=20,
        )
    except Exception as exc:  # noqa: BLE001
        return {
            "ok": False,
            "binary": resolved,
            "error": f"{type(exc).__name__}: {exc}",
        }
    return {
        "ok": proc.returncode == 0,
        "binary": resolved,
        "returncode": proc.returncode,
        "stdout": proc.stdout,
        "stderr": proc.stderr,
    }


def doctor_runtime(
    *,
    runtime_root: Path,
    template_path: Path,
    check_local_vllm_help: bool = False,
    local_vllm_bin: str | None = None,
) -> dict[str, Any]:
    script_path, request_path = _request_paths(runtime_root, template_path)
    state_path = _task_state_path(runtime_root)
    probe_path = _probe_path(runtime_root)
    request_payload = _load_json(request_path)
    state_payload = _load_json(state_path)
    probe_payload = _load_json(probe_path)
    errors: list[str] = []
    warnings: list[str] = []
    info: list[str] = []
    script_text = ""

    if not request_payload:
        errors.append(f"missing request json: {request_path}")
    env = request_payload.get("environment", {}) if request_payload else {}
    if request_payload and not isinstance(env, dict):
        errors.append("request json has non-object environment field")
        env = {}

    request_script_path = Path(request_payload.get("launch_script_path", script_path)) if request_payload else script_path
    if request_script_path != script_path:
        warnings.append(
            f"request launch_script_path differs from derived default: {request_script_path} != {script_path}"
        )
    if not request_script_path.exists():
        errors.append(f"missing launch script: {request_script_path}")
    else:
        script_text = request_script_path.read_text(encoding="utf-8")
        if not request_script_path.stat().st_mode & 0o111:
            warnings.append(f"launch script is not executable: {request_script_path}")
        inline_text = request_payload.get("launch_script_inline")
        if inline_text and inline_text != script_text:
            warnings.append("launch_script_inline differs from the current launch script on disk")

    expected_api_base = _normalize_optional_api_base(request_payload.get("expected_api_base"))
    public_api_base = _normalize_optional_api_base(env.get("PUBLIC_BASE_URL"))
    if expected_api_base and public_api_base and expected_api_base != public_api_base:
        errors.append(f"expected_api_base != environment.PUBLIC_BASE_URL: {expected_api_base} != {public_api_base}")

    public_host = str(env.get("PUBLIC_HOST", ""))
    public_port = str(env.get("PUBLIC_PORT", ""))
    model_path = str(env.get("MODEL_PATH", ""))
    served_model_name = str(env.get("SERVED_MODEL_NAME", ""))
    request_model_name = str(request_payload.get("model_name", "")) if request_payload else ""
    expected_model_name = served_model_name or model_path
    if request_payload and expected_model_name and request_model_name != expected_model_name:
        errors.append(f"request model_name does not match served model id: {request_model_name} != {expected_model_name}")
    if not model_path:
        errors.append("environment.MODEL_PATH is missing")
    if not public_api_base:
        warnings.append("environment.PUBLIC_BASE_URL is missing; clients may have to reconstruct the endpoint manually")
    if public_host == "0.0.0.0":
        warnings.append("environment.PUBLIC_HOST is 0.0.0.0; this is not client-reachable outside the task container")
    if expected_api_base and urlparse(expected_api_base).hostname == "0.0.0.0":
        warnings.append("expected_api_base resolves to 0.0.0.0; record the real externally reachable address after submission")
    if public_port and not public_port.isdigit():
        errors.append(f"environment.PUBLIC_PORT is not numeric: {public_port}")

    if script_text and served_model_name and not _script_mentions_flag(script_text, "--served-model-name"):
        errors.append("launch script does not pass --served-model-name even though SERVED_MODEL_NAME is set")

    if state_payload:
        state_api_base = _normalize_optional_api_base(state_payload.get("api_base"))
        state_model_name = str(state_payload.get("model_name", ""))
        if state_api_base and expected_api_base and state_api_base != expected_api_base:
            warnings.append(f"recorded api_base differs from expected_api_base: {state_api_base} != {expected_api_base}")
        if state_model_name and request_model_name and state_model_name != request_model_name:
            warnings.append(f"recorded model_name differs from request model_name: {state_model_name} != {request_model_name}")
    else:
        warnings.append("missing task state; run the record subcommand after the task is submitted")

    if probe_payload:
        probe_api_base = _normalize_optional_api_base(probe_payload.get("api_base"))
        expected_probe_api_base = _normalize_optional_api_base(
            state_payload.get("api_base") if state_payload else expected_api_base
        )
        if probe_api_base and expected_probe_api_base and probe_api_base != expected_probe_api_base:
            warnings.append(f"probe api_base differs from recorded api_base: {probe_api_base} != {expected_probe_api_base}")
        if not probe_payload.get("ready", False):
            warnings.append("latest probe result is not ready")
    else:
        warnings.append("missing inference_probe.json; endpoint readiness has not been checked yet")

    version_sensitive_flags = [flag for flag in VERSION_SENSITIVE_VLLM_FLAGS if script_text and _script_mentions_flag(script_text, flag)]
    if version_sensitive_flags:
        info.append(
            "launch script uses version-sensitive vLLM flags: " + ", ".join(version_sensitive_flags)
        )

    local_vllm_check: dict[str, Any] | None = None
    if check_local_vllm_help:
        binary = local_vllm_bin or str(env.get("VLLM_BIN", "")) or "vllm"
        local_vllm_check = _run_help_command(binary)
        if local_vllm_check.get("ok"):
            help_text = f"{local_vllm_check.get('stdout', '')}\n{local_vllm_check.get('stderr', '')}"
            missing_flags = [flag for flag in version_sensitive_flags if flag not in help_text]
            local_vllm_check["missing_flags"] = missing_flags
            if missing_flags:
                warnings.append(
                    "local vLLM help does not advertise some script flags: " + ", ".join(missing_flags)
                )
        else:
            warnings.append(f"local vLLM help check failed: {local_vllm_check.get('error', 'unknown error')}")

    return {
        "runtime_root": str(runtime_root),
        "request_path": str(request_path),
        "state_path": str(state_path),
        "probe_path": str(probe_path),
        "launch_script_path": str(request_script_path),
        "request_present": bool(request_payload),
        "state_present": bool(state_payload),
        "probe_present": bool(probe_payload),
        "environment_summary": {
            "model_path": model_path,
            "served_model_name": served_model_name,
            "request_model_name": request_model_name,
            "expected_api_base": expected_api_base,
            "public_base_url": public_api_base,
            "public_host": public_host,
            "public_port": public_port,
            "vllm_bin": str(env.get("VLLM_BIN", "")),
        },
        "version_sensitive_flags": version_sensitive_flags,
        "local_vllm_check": local_vllm_check,
        "errors": errors,
        "warnings": warnings,
        "info": info,
        "ok": not errors,
    }


def _http_get_json(url: str, *, timeout: float) -> tuple[int, Any]:
    req = request.Request(url, method="GET")
    with request.urlopen(req, timeout=timeout) as resp:
        payload = resp.read()
        data = json.loads(payload.decode("utf-8")) if payload else None
        return resp.status, data


def _http_post_json(url: str, payload: dict[str, Any], *, timeout: float) -> tuple[int, Any]:
    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req = request.Request(
        url,
        data=data,
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    with request.urlopen(req, timeout=timeout) as resp:
        body = resp.read()
        decoded = json.loads(body.decode("utf-8")) if body else None
        return resp.status, decoded


def probe_openai_server(
    *,
    api_base: str,
    timeout_s: float,
    poll_s: float,
    request_timeout_s: float,
    chat_model: str | None,
) -> dict[str, Any]:
    deadline = time.time() + timeout_s
    attempts: list[dict[str, Any]] = []
    api_base = api_base.rstrip("/")
    health_url = api_base.removesuffix("/v1") + "/health" if api_base.endswith("/v1") else f"{api_base}/health"
    models_url = f"{api_base}/models" if api_base.endswith("/v1") else f"{api_base}/v1/models"
    chat_url = (
        f"{api_base}/chat/completions" if api_base.endswith("/v1") else f"{api_base}/v1/chat/completions"
    )

    while True:
        attempt: dict[str, Any] = {
            "ts": time.time(),
            "health_url": health_url,
            "models_url": models_url,
        }
        ready = False
        try:
            status, health_payload = _http_get_json(health_url, timeout=request_timeout_s)
            attempt["health_status"] = status
            attempt["health_payload"] = health_payload
        except Exception as exc:  # noqa: BLE001
            attempt["health_error"] = f"{type(exc).__name__}: {exc}"

        try:
            status, models_payload = _http_get_json(models_url, timeout=request_timeout_s)
            attempt["models_status"] = status
            attempt["models_payload"] = models_payload
            ready = status == 200
        except Exception as exc:  # noqa: BLE001
            attempt["models_error"] = f"{type(exc).__name__}: {exc}"

        if ready and chat_model:
            try:
                status, chat_payload = _http_post_json(
                    chat_url,
                    {
                        "model": chat_model,
                        "messages": [{"role": "user", "content": "reply with ok"}],
                        "max_tokens": 8,
                        "temperature": 0,
                    },
                    timeout=request_timeout_s,
                )
                attempt["chat_status"] = status
                attempt["chat_payload"] = chat_payload
                ready = ready and status == 200
            except Exception as exc:  # noqa: BLE001
                attempt["chat_error"] = f"{type(exc).__name__}: {exc}"
                ready = False

        attempt["ready"] = ready
        attempts.append(attempt)
        if ready:
            return {
                "api_base": api_base,
                "ready": True,
                "attempt_count": len(attempts),
                "attempts": attempts,
                "checked_chat": bool(chat_model),
            }

        if time.time() >= deadline:
            return {
                "api_base": api_base,
                "ready": False,
                "attempt_count": len(attempts),
                "attempts": attempts,
                "checked_chat": bool(chat_model),
            }
        time.sleep(poll_s)


def cmd_render(args: argparse.Namespace) -> int:
    runtime_root = _runtime_root(args.runtime_root)
    template_path = _resolve_path_from_repo(args.template)
    script_path, request_path = _request_paths(runtime_root, template_path)
    public_host, public_port, api_base = _public_endpoint(
        host=args.host,
        port=args.port,
        public_host=args.public_host,
        public_port=args.public_port,
        public_base_url=args.public_base_url,
    )

    env_vars: dict[str, str] = {
        "MODEL_PATH": args.model_path,
        "HOST": args.host,
        "PORT": str(args.port),
        "PUBLIC_HOST": public_host,
        "PUBLIC_PORT": public_port,
        "PUBLIC_BASE_URL": api_base,
        "TENSOR_PARALLEL_SIZE": str(args.tensor_parallel_size),
        "DATA_PARALLEL_SIZE": str(args.data_parallel_size),
        "API_SERVER_COUNT": str(args.api_server_count),
        "MAX_MODEL_LEN": str(args.max_model_len),
        "DTYPE": args.dtype,
        "BLOCK_SIZE": str(args.block_size),
        "MAX_NUM_BATCHED_TOKENS": str(args.max_num_batched_tokens),
        "MAX_NUM_SEQS": str(args.max_num_seqs),
        "GPU_MEMORY_UTILIZATION": str(args.gpu_memory_utilization),
        "ENABLE_PREFIX_CACHING": "1" if args.enable_prefix_caching else "0",
        "ENFORCE_EAGER": "1" if args.enforce_eager else "0",
        "ENABLE_AUTO_TOOL_CHOICE": "1" if args.enable_auto_tool_choice else "0",
    }
    optional_env = {
        "SERVED_MODEL_NAME": args.served_model_name,
        "DATA_PARALLEL_SIZE_LOCAL": args.data_parallel_size_local,
        "TOOL_CALL_PARSER": args.tool_call_parser,
        "CONDA_INIT_SCRIPT": args.conda_init_script,
        "CONDA_ENV_NAME": args.conda_env_name,
        "ASCEND_NNAL_ENV": args.ascend_nnal_env,
        "ASCEND_TOOLKIT_ENV": args.ascend_toolkit_env,
        "PYTHON_BIN": args.python_bin,
        "VLLM_BIN": args.vllm_bin,
    }
    for key, value in optional_env.items():
        if value:
            env_vars[key] = str(value)
    for key, value in args.env:
        env_vars[key] = value

    script_text = _build_launch_script(template_path, env_vars)
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text(script_text, encoding="utf-8")
    script_path.chmod(0o755)

    request_payload = {
        "mode": "manual_task_submission",
        "platform_name": args.platform_name,
        "image": args.image,
        "resource_profile": args.resource_profile,
        "model_name": args.model_name or args.served_model_name or args.model_path,
        "expected_api_base": api_base,
        "environment": env_vars,
        "launch_script_path": str(script_path),
        "launch_script_inline": script_text,
        "submission_notes": args.notes,
        "manual_submission_checklist": [
            "Create a task with the specified image and resource profile.",
            "Set the environment variables from the generated request JSON.",
            "Use the generated launch script as the task entrypoint.",
            "Expose the configured port and record the final API_BASE.",
            "After the task is running, call the 'record' subcommand to persist task_id/api_base locally.",
        ],
    }
    _write_json(request_path, request_payload)

    if args.public_base_url is None and public_host == "0.0.0.0":
        print(
            "warning: PUBLIC_HOST resolved to 0.0.0.0; pass --public-host or --public-base-url "
            "if the task needs a client-reachable endpoint recorded.",
            file=sys.stderr,
        )

    print(f"launch_script={script_path}")
    print(f"request_json={request_path}")
    print(f"expected_api_base={api_base}")
    return 0


def cmd_record(args: argparse.Namespace) -> int:
    runtime_root = _runtime_root(args.runtime_root)
    template_path = _resolve_path_from_repo(args.template)
    request_path = _request_paths(runtime_root, template_path)[1]
    existing = _load_json(request_path)
    state_path = _task_state_path(runtime_root)
    api_base = args.api_base.rstrip("/") if args.api_base else existing.get("expected_api_base", "")
    if api_base and not api_base.endswith("/v1"):
        api_base = api_base.rstrip("/") + "/v1"
    payload = {
        "task_id": args.task_id,
        "status": args.status,
        "api_base": api_base,
        "model_name": args.model_name or existing.get("model_name", ""),
        "image": args.image or existing.get("image", ""),
        "resource_profile": args.resource_profile or existing.get("resource_profile", ""),
        "remote_log_url": args.remote_log_url,
        "notes": args.notes,
        "updated_at": time.time(),
    }
    _write_json(state_path, payload)
    print(f"task_state={state_path}")
    return 0


def cmd_probe(args: argparse.Namespace) -> int:
    runtime_root = _runtime_root(args.runtime_root)
    state = _load_json(_task_state_path(runtime_root))
    api_base = args.api_base or state.get("api_base")
    if not api_base:
        print("No api_base provided and no inference_task.json present.", file=sys.stderr)
        return 2
    chat_model = args.chat_model or state.get("model_name") if args.check_chat else None
    result = probe_openai_server(
        api_base=str(api_base),
        timeout_s=args.timeout,
        poll_s=args.poll_interval,
        request_timeout_s=args.request_timeout,
        chat_model=str(chat_model) if chat_model else None,
    )
    _write_json(_probe_path(runtime_root), result)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0 if result["ready"] else 1


def cmd_doctor(args: argparse.Namespace) -> int:
    runtime_root = _runtime_root(args.runtime_root)
    template_path = _resolve_path_from_repo(args.template)
    result = doctor_runtime(
        runtime_root=runtime_root,
        template_path=template_path,
        check_local_vllm_help=args.check_local_vllm_help,
        local_vllm_bin=args.local_vllm_bin,
    )
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0 if result["ok"] else 1


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Prepare and track manually submitted remote inference tasks for OpenAI-compatible evaluation servers."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    render = subparsers.add_parser("render", help="Generate a launch script and a submission request JSON.")
    render.add_argument("--runtime-root", required=True)
    render.add_argument("--template", default="sh/templates/launch_vllm_task_ascend.sh")
    render.add_argument("--platform-name", default="internal-web-ui")
    render.add_argument("--image", required=True)
    render.add_argument("--resource-profile", required=True)
    render.add_argument("--model-path", required=True)
    render.add_argument("--model-name")
    render.add_argument(
        "--served-model-name",
        help="Optional vLLM model id exposed to clients. Use this when the client-side MODEL_NAME should differ from the container-local MODEL_PATH.",
    )
    render.add_argument("--host", default="0.0.0.0")
    render.add_argument("--port", type=int, default=8000)
    render.add_argument("--public-host")
    render.add_argument("--public-port", type=int)
    render.add_argument("--public-base-url")
    render.add_argument("--tensor-parallel-size", type=int, default=1)
    render.add_argument("--data-parallel-size", type=int, default=1)
    render.add_argument("--data-parallel-size-local")
    render.add_argument("--api-server-count", type=int, default=1)
    render.add_argument("--max-model-len", type=int, default=32768)
    render.add_argument("--dtype", default="bfloat16")
    render.add_argument("--block-size", type=int, default=128)
    render.add_argument("--max-num-batched-tokens", type=int, default=4096)
    render.add_argument("--max-num-seqs", type=int, default=128)
    render.add_argument("--gpu-memory-utilization", type=float, default=0.90)
    render.add_argument("--enable-prefix-caching", action="store_true")
    render.add_argument("--enforce-eager", action="store_true")
    render.add_argument("--enable-auto-tool-choice", action="store_true")
    render.add_argument("--tool-call-parser")
    render.add_argument("--conda-init-script")
    render.add_argument("--conda-env-name")
    render.add_argument("--ascend-nnal-env")
    render.add_argument("--ascend-toolkit-env")
    render.add_argument("--python-bin")
    render.add_argument("--vllm-bin")
    render.add_argument("--env", action="append", type=_parse_env_pair, default=[])
    render.add_argument("--notes", default="")
    render.set_defaults(func=cmd_render)

    record = subparsers.add_parser("record", help="Persist task_id/api_base for a manually submitted task.")
    record.add_argument("--runtime-root", required=True)
    record.add_argument("--template", default="sh/templates/launch_vllm_task_ascend.sh")
    record.add_argument("--task-id", required=True)
    record.add_argument("--status", default="running")
    record.add_argument("--api-base")
    record.add_argument("--model-name")
    record.add_argument("--image")
    record.add_argument("--resource-profile")
    record.add_argument("--remote-log-url", default="")
    record.add_argument("--notes", default="")
    record.set_defaults(func=cmd_record)

    probe = subparsers.add_parser("probe", help="Probe an OpenAI-compatible endpoint and write inference_probe.json.")
    probe.add_argument("--runtime-root", required=True)
    probe.add_argument("--api-base")
    probe.add_argument("--timeout", type=float, default=600.0)
    probe.add_argument("--poll-interval", type=float, default=5.0)
    probe.add_argument("--request-timeout", type=float, default=10.0)
    probe.add_argument("--check-chat", action="store_true")
    probe.add_argument("--chat-model")
    probe.set_defaults(func=cmd_probe)

    doctor = subparsers.add_parser(
        "doctor",
        help="Validate remote inference task artifacts for obvious config mismatches before running eval.",
    )
    doctor.add_argument("--runtime-root", required=True)
    doctor.add_argument("--template", default="sh/templates/launch_vllm_task_ascend.sh")
    doctor.add_argument("--check-local-vllm-help", action="store_true")
    doctor.add_argument("--local-vllm-bin")
    doctor.set_defaults(func=cmd_doctor)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
