set -x

DATA_DIR="/mnt/shared_storage/datasets/r2e-1000"
train_data="${DATA_DIR}/train.parquet"
test_data="${DATA_DIR}/validation.parquet"

uv run --isolated --extra verl --env-file .env -m skyrl_agent.integrations.verl.verl_main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=$train_data \
    data.val_files=$test_data \
    data.train_batch_size=4 \
    data.max_prompt_length=4096 \
    data.max_response_length=35000 \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    data.return_raw_chat=True \
    actor_rollout_ref.model.path=Qwen/Qwen3-8B \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=4 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=2 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.mode=async \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.7 \
    actor_rollout_ref.rollout.n=1 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=False \
    trainer.val_before_train=false \
    trainer.critic_warmup=0 \
    trainer.logger='["console","wandb"]' \
    trainer.project_name='verl_grpo_skyagent' \
    trainer.experiment_name='qwen2.5_1.5b_function_rm' \
    trainer.n_gpus_per_node=4 \
    trainer.nnodes=1 \
    trainer.save_freq=1 \
    trainer.test_freq=5 \
    trainer.total_epochs=15 \
    trainer.default_local_dir=/mnt/local_storage/checkpoints/verl_grpo_skyagent/qwen2.5_1.5b_function_rm \
    trainer.rollout_data_dir=/mnt/local_storage/rollouts/verl_grpo_skyagent/qwen2.5_1.5b_function_rm \
    trainer.validation_data_dir=/mnt/local_storage/rollouts/verl_grpo_skyagent/qwen2.5_1.5b_function_rm_val \
    +skyrl_agent.task_yaml="./examples/run_verl/verl_oh.yaml" \
    +skyrl_agent.num_trajectories=4 \
    +trainer.remote_anyscale_upload=True \
    +trainer.remote_upload_dir=remote_ckpts/verl_grpo_skyagent/qwen2.5_1.5b_function_rm $@
